### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by fusionneur** [jspw/Ubuntu-Launcher#2]
Fresh install, won't start..

**Comment by fusionneur** [comment]
Only a picture with a feline is shown

**Comment by jspw** [comment]
I have solved the issue.
Just pull down and apps list will be refreshed.

**Comment by jspw** [comment]
Check this version [1.10](https://github.com/jspw/Ubuntu-Launcher/releases/tag/1.10)

**Comment by fusionneur** [comment]
i get same behavior on latest github release 1.10

**Comment by jspw** [comment]
I don't know . Its working fine in my Huawei y9 2018 and Pixel 2 (Mobile Emulator).
Can you provide more information about your phone ?

**Comment by fusionneur** [comment]
I realized that if I long press on very left side of the screen and slowly slide to the right, the left pane appears.

This is however extremely unintuitive - especially for devices that have gestures on, where sliding from the edge of the screen actually translates to "BACK"

Other than this, I suggest some features that could make the launcher much better:

1. ability to create custom categories (and delete default pinned ones) on left pane and organize apps per category
2. settings icon opens settings for the launcher itself instead of android settings
3. left pane should be able to be opened by sliding anywhere on the screen not only to the edge
4. allow live wallpapers and normal wallpapers
5. more customization freedom (change icons by longpressing, backup/restore, move icons, sort,filter, search ..)

Launchers as reference : smart launcher (playstore) and LukeLauncher (fdroid)

Cheers

**Comment by jspw** [comment]
Thanks. I will consider your suggestions in the next update.
