### ISSUE TITLE
HomeScreen slidebar icons doesnt work with some phone models

### ISSUE THREAD

**Issue by jspw** [jspw/Ubuntu-Launcher#4]
1. Xiaomi Redmi Note 7, Android 10

2. Aka TCL L10

3. Samsung Note 3

**Comment by Imdipankar** [comment]
![Screenshot_20210611-220429.jpg](https://user-images.githubusercontent.com/70141595/121720689-025d3200-cb01-11eb-986e-94457867c417.jpg)


Not working on Samsung Galaxy A21s

**Comment by jspw** [comment]
@Imdipankar  slide from left to right doesnt show slidebar?

**Comment by Imdipankar** [comment]
Yes

**Comment by jspw** [comment]
fixed in #10
