### ISSUE TITLE
did the packageName just change intentionally?

### ISSUE THREAD

**Issue by IzzySoft** [jspw/Ubuntu-Launcher#8]
it seems the packageName just changed from `com.example.launcher` to `com.ubuntu.launcher`, which effectively makes it a different app that needs to be re-installed (no update possible). As the release notes do not mention this fact: was that done intentionally? And will the new name "stick"?

**Comment by jspw** [comment]
Sorry i forgot to mention that in new release. I came to realise that the packageName "com.example.launcher" is already registered in another android launcher and this will be a conflict  . So i had to chnage the packagename and it will be sticked to the new packagename.

**Comment by IzzySoft** [comment]
Makes sense, thanks! Just wanted to make sure before "renaming" it in my repo :wink:
